name: barnard_demo
description: Demo for the Barnard Dart package (mock implementation).
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  barnard:
    path: ../../../packages/dart/barnard
