name: Dart CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter plugin (analyze/test)
        working-directory: packages/dart/barnard
        run: |
          flutter --version
          flutter pub get
          flutter analyze
          flutter test
      - name: Flutter example (analyze)
        working-directory: examples/flutter/barnard_poc
        run: |
          flutter pub get
          flutter analyze
          flutter test
          flutter build apk --debug

  smoke:
    runs-on: ubuntu-latest
    needs: [flutter]
    defaults:
      run:
        working-directory: examples/dart/barnard_demo
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: dart run bin/main.dart
